export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS'
export const SET_ALL_PLAYERS = 'SET_ALL_PLAYERS'
export const GET_SELECTED_CLUBS = 'GET_SELECTED_CLUBS'
export const SET_SELECTED_CLUBS = 'SET_SELECTED_CLUBS'
